// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package collection_model

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type collection_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var CollectionBinding = collection_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 356145602109352620,
}

// Collection_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Collection_ = struct {
	Id       *objectbox.PropertyUint64
	Name     *objectbox.PropertyString
	Genre    *objectbox.PropertyString
	ImageUrl *objectbox.PropertyString
	Progress *objectbox.PropertyFloat64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &CollectionBinding.Entity,
		},
	},
	Name: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &CollectionBinding.Entity,
		},
	},
	Genre: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &CollectionBinding.Entity,
		},
	},
	ImageUrl: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &CollectionBinding.Entity,
		},
	},
	Progress: &objectbox.PropertyFloat64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &CollectionBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (collection_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (collection_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Collection", 1, 356145602109352620)
	model.Property("Id", 6, 1, 8114277743437648896)
	model.PropertyFlags(1)
	model.Property("Name", 9, 2, 1273595762963190650)
	model.Property("Genre", 9, 3, 6044536122572584859)
	model.Property("ImageUrl", 9, 4, 5273189021012851648)
	model.Property("Progress", 8, 5, 5400440269423910839)
	model.EntityLastPropertyId(5, 5400440269423910839)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (collection_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Collection).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (collection_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Collection).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (collection_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (collection_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Collection)
	var offsetName = fbutils.CreateStringOffset(fbb, obj.Name)
	var offsetGenre = fbutils.CreateStringOffset(fbb, obj.Genre)
	var offsetImageUrl = fbutils.CreateStringOffset(fbb, obj.ImageUrl)

	// build the FlatBuffers object
	fbb.StartObject(5)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetName)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetGenre)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetImageUrl)
	fbutils.SetFloat64Slot(fbb, 4, obj.Progress)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (collection_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Collection' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &Collection{
		Id:       propId,
		Name:     fbutils.GetStringSlot(table, 6),
		Genre:    fbutils.GetStringSlot(table, 8),
		ImageUrl: fbutils.GetStringSlot(table, 10),
		Progress: fbutils.GetFloat64Slot(table, 12),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (collection_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Collection, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (collection_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Collection), nil)
	}
	return append(slice.([]*Collection), object.(*Collection))
}

// Box provides CRUD access to Collection objects
type CollectionBox struct {
	*objectbox.Box
}

// BoxForCollection opens a box of Collection objects
func BoxForCollection(ob *objectbox.ObjectBox) *CollectionBox {
	return &CollectionBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Collection.Id property on the passed object will be assigned the new ID as well.
func (box *CollectionBox) Put(object *Collection) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Collection.Id property on the passed object will be assigned the new ID as well.
func (box *CollectionBox) Insert(object *Collection) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *CollectionBox) Update(object *Collection) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *CollectionBox) PutAsync(object *Collection) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Collection.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Collection.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *CollectionBox) PutMany(objects []*Collection) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *CollectionBox) Get(id uint64) (*Collection, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Collection), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *CollectionBox) GetMany(ids ...uint64) ([]*Collection, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Collection), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *CollectionBox) GetManyExisting(ids ...uint64) ([]*Collection, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Collection), nil
}

// GetAll reads all stored objects
func (box *CollectionBox) GetAll() ([]*Collection, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Collection), nil
}

// Remove deletes a single object
func (box *CollectionBox) Remove(object *Collection) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *CollectionBox) RemoveMany(objects ...*Collection) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Collection_ struct to create conditions.
// Keep the *CollectionQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *CollectionBox) Query(conditions ...objectbox.Condition) *CollectionQuery {
	return &CollectionQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Collection_ struct to create conditions.
// Keep the *CollectionQuery if you intend to execute the query multiple times.
func (box *CollectionBox) QueryOrError(conditions ...objectbox.Condition) (*CollectionQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &CollectionQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See CollectionAsyncBox for more information.
func (box *CollectionBox) Async() *CollectionAsyncBox {
	return &CollectionAsyncBox{AsyncBox: box.Box.Async()}
}

// CollectionAsyncBox provides asynchronous operations on Collection objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type CollectionAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForCollection creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use CollectionBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForCollection(ob *objectbox.ObjectBox, timeoutMs uint64) *CollectionAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &CollectionAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *CollectionAsyncBox) Put(object *Collection) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *CollectionAsyncBox) Insert(object *Collection) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *CollectionAsyncBox) Update(object *Collection) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *CollectionAsyncBox) Remove(object *Collection) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Collection which Id is either 42 or 47:
//
// box.Query(Collection_.Id.In(42, 47)).Find()
type CollectionQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *CollectionQuery) Find() ([]*Collection, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Collection), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *CollectionQuery) Offset(offset uint64) *CollectionQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *CollectionQuery) Limit(limit uint64) *CollectionQuery {
	query.Query.Limit(limit)
	return query
}
