// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection_model} from '../models';

export function CreateCollection(arg1:string,arg2:string,arg3:string,arg4:number):Promise<collection_model.Collection>;

export function DeleteCollection(arg1:number):Promise<void>;

export function GetCollection(arg1:number):Promise<collection_model.Collection>;

export function GetCollections():Promise<Array<collection_model.Collection>>;

export function UpdateCollection(arg1:collection_model.Collection):Promise<void>;
